/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Apartment: typeof import('./components/ApartmentCmp.vue')['default']
    ApartmentCmp: typeof import('./components/ApartmentCmp.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Booking: typeof import('./components/BookingCmp.vue')['default']
    BookingCmp: typeof import('./components/BookingCmp.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Landlord: typeof import('./components/LandlordCmp.vue')['default']
    LandlordCmp: typeof import('./components/LandlordCmp.vue')['default']
    ManageProperties: typeof import('./components/ManageProperties.vue')['default']
    ManageTenants: typeof import('./components/ManageTenants.vue')['default']
    Property: typeof import('./components/PropertyCmp.vue')['default']
    PropertyCmp: typeof import('./components/PropertyCmp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tenant: typeof import('./components/TenantCmp.vue')['default']
    TenantCmp: typeof import('./components/TenantCmp.vue')['default']
  }
}
