/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/apartment': RouteRecordInfo<'/apartment', '/apartment', Record<never, never>, Record<never, never>>,
    '/booking': RouteRecordInfo<'/booking', '/booking', Record<never, never>, Record<never, never>>,
    '/landlord': RouteRecordInfo<'/landlord', '/landlord', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/logout': RouteRecordInfo<'/logout', '/logout', Record<never, never>, Record<never, never>>,
    '/property': RouteRecordInfo<'/property', '/property', Record<never, never>, Record<never, never>>,
    '/tenant': RouteRecordInfo<'/tenant', '/tenant', Record<never, never>, Record<never, never>>,
  }
}
